### ISSUE TITLE
what is the label value of curb in the semantic kitti link which you are provided?

### ISSUE THREAD

**Issue by yangxh31** [guoyangzhao/CurbNet#2]

**Comment by guoyangzhao** [comment]
The curb category has been added, assigning a value of 3 to the Curb label.
When using API visualization, please add 3: "curb" to label: in "config/semantic-kitti.yaml" to increase the visualization of curb.

**Comment by yangxh31** [comment]
> The curb category has been added, assigning a value of 3 to the Curb label. When using API visualization, please add 3: "curb" to label: in "config/semantic-kitti.yaml" to increase the visualization of curb.

thanks. i got it. 
semantic_label = label & 0xFFFF
instance_label = label >> 16.
﻿Looking forward to the　release of the code!
